AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-nextjs-lambda

  Sample SAM Template for sam-nextjs-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  NextjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Architectures:
      - arm64
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: 
        Origins: 
        - ConnectionAttempts: 3
          ConnectionTimeout: 10
          CustomOriginConfig: 
            HTTPPort: 80
            HTTPSPort: 443
            OriginKeepaliveTimeout: 5
            OriginProtocolPolicy: "https-only"
            OriginReadTimeout: 30
            OriginSSLProtocols: 
            - "TLSv1.2"
          DomainName: !Sub ${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
          Id: 'NextjsAPIGW'
          OriginPath: ""
        - ConnectionAttempts: 3
          ConnectionTimeout: 10
          CustomOriginConfig: 
            HTTPPort: 80
            HTTPSPort: 443
            OriginKeepaliveTimeout: 5
            OriginProtocolPolicy: "https-only"
            OriginReadTimeout: 30
            OriginSSLProtocols: 
            - "TLSv1.2"
          DomainName: !ImportValue NestjsApiDomain
          Id: 'NestjsAPIGW'
          OriginPath: ""
        DefaultCacheBehavior: 
          AllowedMethods: 
          - "HEAD"
          - "GET"
          CachedMethods: 
          - "HEAD"
          - "GET"
          Compress: true
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          OriginRequestPolicyId: "b689b0a8-53d0-40ab-baf2-68738e2966ac"
          SmoothStreaming: false
          TargetOriginId: "NextjsAPIGW"
          ViewerProtocolPolicy: "allow-all"
        CacheBehaviors: 
        - AllowedMethods: 
          - "HEAD"
          - "GET"
          Compress: true
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          OriginRequestPolicyId: "b689b0a8-53d0-40ab-baf2-68738e2966ac"
          PathPattern: "/api/*"
          SmoothStreaming: false
          TargetOriginId: "NestjsAPIGW"
          ViewerProtocolPolicy: "allow-all"
        Comment: ""
        PriceClass: "PriceClass_All"
        Enabled: true
        # ViewerCertificate: 
        #   CloudFrontDefaultCertificate: true
        #   MinimumProtocolVersion: "TLSv1"
        #   SslSupportMethod: "vip"
        # Restrictions: 
        #   GeoRestriction: 
        #     RestrictionType: "none"
        HttpVersion: "http2"
        DefaultRootObject: ""
        IPV6Enabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NextjsApi:
    Description: API Gateway endpoint URL
    Value: !GetAtt ServerlessHttpApi.ApiEndpoint
  NextjsApiDomain:
    Description: API Gateway endpoint Domain
    Value: !Sub "${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: NextjsApiDomain
  NextjsApiAppId:
    Description: API Gateway AppId
    Value: !GetAtt ServerlessHttpApi.ApiId
    Export:
      Name: NextjsApiAppId
  CloudFront:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"